include:
  - apps/docker-compose-apps.yml
  - monitoring/docker-compose-monitoring.yml

services:
  traefik:
    image: traefik:v3.5.2
    container_name: traefik
    ports:
      - "8050:80"
      - "8082:8080"
      - "9100:9100"
    networks:
      - file-storage-network
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "aden-traefik"
      tsdproxy.ephemeral: "false"
      tsdproxy.container_port: "80"
    command: 
    - "--providers.docker=true" 
    - "--entrypoints.web.address=:80" 
    - "--entrypoints.websecure.address=:443" 
    - "--entrypoints.metrics.address=:8082" 
    - "--entrypoints.traefik.address=:8080"
    volumes:
      - ./traefik-v3.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    networks:
      - file-storage-network
    environment:
      - TSD_AUTHKEY=${TS_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ${PWD}/config:/config
    restart: unless-stopped
    ports:
      - "8081:8080"

networks:
  file-storage-network:
    driver: bridge

volumes:
  datadir: