services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: huutrucnguyen0508/storage-server-nginx:1.0.0
    ports:
      - "8080:80"
    volumes:
      # Mount uploads directory for direct file serving
      - F:\web_uploads:/app/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - file-storage-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: huutrucnguyen0508/storage-server-frontend:1.0.2
    environment:
      - NODE_ENV=production
    networks:
      - file-storage-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: huutrucnguyen0508/storage-server-backend:1.0.1
    environment:
      - NODE_ENV=production
    volumes:
      # Mount F: drive for persistent storage with folder support
      - F:\web_uploads:/app/uploads
      - F:\web_uploads\database:/app/database
    depends_on:
      - database
    networks:
      - file-storage-network
    restart: unless-stopped

  database:
    image: alpine:latest
    command: /bin/sh -c "while true; do sleep 30; done"
    volumes:
      # Mount F: drive for database persistence
      - F:\web_uploads\database:/data
    networks:
      - file-storage-network
    restart: unless-stopped

networks:
  file-storage-network:
    driver: bridge

volumes:
  file-storage-data:
    driver: local
