# Traefik static configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: file-storage-network
    watch: true
    allowEmptyServices: true

accessLog: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# tracing:
#   serviceName: traefik
#   jaeger:
#     samplingType: const
#     samplingParam: 1.0
#     localAgentHostPort: jaeger:14268
#     traceContextHeaderName: uber-trace-id